
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> bg = BaseGeometry()

>>> type(bg) == BaseGeometry
True

>>> bg.integer_validator("test", 5)

>>> bg.integer_validator("test", 5.5)
Traceback (most recent call last):
TypeError: test must be an integer

>>> bg.integer_validator("test", "hello")
Traceback (most recent call last):
TypeError: test must be an integer

>>> bg.integer_validator("test", 10)

>>> bg.integer_validator("test", 0)
Traceback (most recent call last):
ValueError: test must be greater than 0

>>> bg.integer_validator("test", -5)
Traceback (most recent call last):
ValueError: test must be greater than 0

>>> bg.integer_validator("test", "nassim")
Traceback (most recent call last):
TypeError: test must be an integer

>>> bg.integer_validator(10)
Traceback (most recent call last):
TypeError: BaseGeometry.integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator(10.5)
Traceback (most recent call last):
TypeError: BaseGeometry.integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator(7.5, 7.5)
Traceback (most recent call last):
TypeError: 7.5 must be an integer

>>> bg.integer_validator(10, 10)

>>> bg.integer_validator(10, "string")
Traceback (most recent call last):
TypeError: 10 must be an integer

>>> bg.integer_validator(10, 7, 8)
Traceback (most recent call last):
TypeError: BaseGeometry.integer_validator() takes 3 positional arguments but 4 were given

>>> bg.integer_validator(10.5, "string")
Traceback (most recent call last):
TypeError: 10.5 must be an integer

>>> bg.integer_validator("sch", [5])
Traceback (most recent call last):
TypeError: sch must be an integer

>>> bg.integer_validator()
Traceback (most recent call last):
TypeError: BaseGeometry.integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> type(BaseGeometry.__dict__['area'])
<class 'function'>'

>>> bg.integer_validator("Nas", None)
Traceback (most recent call last):
TypeError: Nas must be an integer

>>> bg.integer_validator("", 1)

>>> bg.integer_validator(None, 3)

>>> bg.integer_validator("Nass", (2, 2))
Traceback (most recent call last):
TypeError: Nass must be an integer

>>> bg.integer_validator("Nas", {5, 10})
Traceback (most recent call last):
TypeError: Nas must be an integer
